version: '3.9'
services:
  database:
    image: postgres
    container_name: notarium
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0705
      - POSTGRES_DB=notarium
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local          